/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request, Response } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FileInterceptor } from "@nestjs/platform-express";
import { WedInvPaymentService } from "../wedInvPayment.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { WedInvPaymentCreateInput } from "./WedInvPaymentCreateInput";
import { WedInvPayment } from "./WedInvPayment";
import { WedInvPaymentFindManyArgs } from "./WedInvPaymentFindManyArgs";
import { WedInvPaymentWhereUniqueInput } from "./WedInvPaymentWhereUniqueInput";
import { WedInvPaymentUpdateInput } from "./WedInvPaymentUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class WedInvPaymentControllerBase {
  constructor(
    protected readonly service: WedInvPaymentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: WedInvPayment })
  @nestAccessControl.UseRoles({
    resource: "WedInvPayment",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: WedInvPaymentCreateInput,
  })
  async createWedInvPayment(
    @common.Body() data: WedInvPaymentCreateInput
  ): Promise<WedInvPayment> {
    return await this.service.createWedInvPayment({
      data: {
        ...data,

        dtPaymentMethod: data.dtPaymentMethod
          ? {
              connect: data.dtPaymentMethod,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,

        wedInv: data.wedInv
          ? {
              connect: data.wedInv,
            }
          : undefined,
      },
      select: {
        accountName: true,
        accountNo: true,
        amount: true,
        createdAt: true,

        dtPaymentMethod: {
          select: {
            id: true,
          },
        },

        evidence: true,
        id: true,
        noRef: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        wedInv: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [WedInvPayment] })
  @ApiNestedQuery(WedInvPaymentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "WedInvPayment",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async wedInvPayments(
    @common.Req() request: Request
  ): Promise<WedInvPayment[]> {
    const args = plainToClass(WedInvPaymentFindManyArgs, request.query);
    return this.service.wedInvPayments({
      ...args,
      select: {
        accountName: true,
        accountNo: true,
        amount: true,
        createdAt: true,

        dtPaymentMethod: {
          select: {
            id: true,
          },
        },

        evidence: true,
        id: true,
        noRef: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        wedInv: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: WedInvPayment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WedInvPayment",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async wedInvPayment(
    @common.Param() params: WedInvPaymentWhereUniqueInput
  ): Promise<WedInvPayment | null> {
    const result = await this.service.wedInvPayment({
      where: params,
      select: {
        accountName: true,
        accountNo: true,
        amount: true,
        createdAt: true,

        dtPaymentMethod: {
          select: {
            id: true,
          },
        },

        evidence: true,
        id: true,
        noRef: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        wedInv: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: WedInvPayment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WedInvPayment",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: WedInvPaymentUpdateInput,
  })
  async updateWedInvPayment(
    @common.Param() params: WedInvPaymentWhereUniqueInput,
    @common.Body() data: WedInvPaymentUpdateInput
  ): Promise<WedInvPayment | null> {
    try {
      return await this.service.updateWedInvPayment({
        where: params,
        data: {
          ...data,

          dtPaymentMethod: data.dtPaymentMethod
            ? {
                connect: data.dtPaymentMethod,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,

          wedInv: data.wedInv
            ? {
                connect: data.wedInv,
              }
            : undefined,
        },
        select: {
          accountName: true,
          accountNo: true,
          amount: true,
          createdAt: true,

          dtPaymentMethod: {
            select: {
              id: true,
            },
          },

          evidence: true,
          id: true,
          noRef: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          wedInv: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: WedInvPayment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WedInvPayment",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteWedInvPayment(
    @common.Param() params: WedInvPaymentWhereUniqueInput
  ): Promise<WedInvPayment | null> {
    try {
      return await this.service.deleteWedInvPayment({
        where: params,
        select: {
          accountName: true,
          accountNo: true,
          amount: true,
          createdAt: true,

          dtPaymentMethod: {
            select: {
              id: true,
            },
          },

          evidence: true,
          id: true,
          noRef: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          wedInv: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Put(":id/evidence")
  @common.UseInterceptors(FileInterceptor("file"))
  @swagger.ApiConsumes("multipart/form-data")
  @swagger.ApiBody({
    schema: {
      type: "object",

      properties: {
        file: {
          type: "string",
          format: "binary",
        },
      },
    },
  })
  @swagger.ApiParam({
    name: "id",
    type: "string",
    required: true,
  })
  @swagger.ApiCreatedResponse({
    type: WedInvPayment,
    status: "2XX",
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  async uploadEvidence(
    @common.Param()
    params: WedInvPaymentWhereUniqueInput,
    @common.UploadedFile()
    file: Express.Multer.File
  ): Promise<WedInvPayment> {
    return this.service.uploadEvidence(
      {
        where: params,
      },
      Object.assign(file, {
        filename: file.originalname,
      })
    );
  }

  @common.Get(":id/evidence")
  @swagger.ApiParam({
    name: "id",
    type: "string",
    required: true,
  })
  @swagger.ApiOkResponse({
    type: common.StreamableFile,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  async downloadEvidence(
    @common.Param()
    params: WedInvPaymentWhereUniqueInput,
    @common.Res({
      passthrough: true,
    })
    res: Response
  ): Promise<common.StreamableFile> {
    const result = await this.service.downloadEvidence({
      where: params,
    });

    if (result === null) {
      throw new errors.NotFoundException(
        "No resource was found for ",
        JSON.stringify(params)
      );
    }

    res.setHeader(
      "Content-Disposition",
      `attachment; filename=${result.filename}`
    );
    res.setHeader("Content-Type", result.mimetype);
    return result.stream;
  }

  @common.Delete(":id/evidence")
  @swagger.ApiOkResponse({
    type: WedInvPayment,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  async deleteEvidence(
    @common.Param()
    params: WedInvPaymentWhereUniqueInput
  ): Promise<WedInvPayment> {
    return this.service.deleteEvidence({
      where: params,
    });
  }
}
