/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, IsEnum, ValidateNested } from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { EnumUserStatus } from "./EnumUserStatus";
import { WedInvPaymentCreateNestedManyWithoutUsersInput } from "./WedInvPaymentCreateNestedManyWithoutUsersInput";
import { Type } from "class-transformer";
import { WedInvCreateNestedManyWithoutUsersInput } from "./WedInvCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fullName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
    enum: EnumUserStatus,
  })
  @IsEnum(EnumUserStatus)
  @IsOptional()
  @Field(() => EnumUserStatus, {
    nullable: true,
  })
  status?: "Active" | "Nonactive" | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;

  @ApiProperty({
    required: false,
    type: () => WedInvPaymentCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => WedInvPaymentCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => WedInvPaymentCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  wedInvPayments?: WedInvPaymentCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => WedInvCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => WedInvCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => WedInvCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  wedInvs?: WedInvCreateNestedManyWithoutUsersInput;
}

export { UserCreateInput as UserCreateInput };
