/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, IsEnum, ValidateNested } from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { EnumUserStatus } from "./EnumUserStatus";
import { WedInvPaymentUpdateManyWithoutUsersInput } from "./WedInvPaymentUpdateManyWithoutUsersInput";
import { Type } from "class-transformer";
import { WedInvUpdateManyWithoutUsersInput } from "./WedInvUpdateManyWithoutUsersInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fullName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    enum: EnumUserStatus,
  })
  @IsEnum(EnumUserStatus)
  @IsOptional()
  @Field(() => EnumUserStatus, {
    nullable: true,
  })
  status?: "Active" | "Nonactive" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;

  @ApiProperty({
    required: false,
    type: () => WedInvPaymentUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => WedInvPaymentUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => WedInvPaymentUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  wedInvPayments?: WedInvPaymentUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => WedInvUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => WedInvUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => WedInvUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  wedInvs?: WedInvUpdateManyWithoutUsersInput;
}

export { UserUpdateInput as UserUpdateInput };
