/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  WedInvGallery as PrismaWedInvGallery,
  WedInv as PrismaWedInv,
} from "@prisma/client";
import { LocalStorageService } from "src/storage/providers/local/local.storage.service";
import { InputJsonValue } from "src/types";
import { FileDownload, FileUpload } from "src/storage/base/storage.types";
import { LocalStorageFile } from "src/storage/providers/local/local.storage.types";

export class WedInvGalleryServiceBase {
  constructor(
    protected readonly prisma: PrismaService,
    protected readonly localStorageService: LocalStorageService
  ) {}

  async count(
    args: Omit<Prisma.WedInvGalleryCountArgs, "select">
  ): Promise<number> {
    return this.prisma.wedInvGallery.count(args);
  }

  async wedInvGalleries<T extends Prisma.WedInvGalleryFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.WedInvGalleryFindManyArgs>
  ): Promise<PrismaWedInvGallery[]> {
    return this.prisma.wedInvGallery.findMany<Prisma.WedInvGalleryFindManyArgs>(
      args
    );
  }
  async wedInvGallery<T extends Prisma.WedInvGalleryFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.WedInvGalleryFindUniqueArgs>
  ): Promise<PrismaWedInvGallery | null> {
    return this.prisma.wedInvGallery.findUnique(args);
  }
  async createWedInvGallery<T extends Prisma.WedInvGalleryCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.WedInvGalleryCreateArgs>
  ): Promise<PrismaWedInvGallery> {
    return this.prisma.wedInvGallery.create<T>(args);
  }
  async updateWedInvGallery<T extends Prisma.WedInvGalleryUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.WedInvGalleryUpdateArgs>
  ): Promise<PrismaWedInvGallery> {
    return this.prisma.wedInvGallery.update<T>(args);
  }
  async deleteWedInvGallery<T extends Prisma.WedInvGalleryDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.WedInvGalleryDeleteArgs>
  ): Promise<PrismaWedInvGallery> {
    return this.prisma.wedInvGallery.delete(args);
  }

  async uploadPhoto<T extends Prisma.WedInvGalleryFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.WedInvGalleryFindUniqueArgs>,
    file: FileUpload
  ): Promise<PrismaWedInvGallery> {
    file.filename = `profilePicture-${args.where.id}.${file.filename
      .split(".")
      .pop()}`;
    const containerPath = "/Wed Inv/Galleries/";
    const photo = await this.localStorageService.uploadFile(
      file,
      [],
      10000000,
      containerPath
    );

    return await this.prisma.wedInvGallery.update({
      where: args.where,

      data: {
        photo: photo as InputJsonValue,
      },
    });
  }

  async downloadPhoto<T extends Prisma.WedInvGalleryFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.WedInvGalleryFindUniqueArgs>
  ): Promise<FileDownload> {
    const { photo } = await this.prisma.wedInvGallery.findUniqueOrThrow({
      where: args.where,
    });

    return await this.localStorageService.downloadFile(
      photo as unknown as LocalStorageFile
    );
  }

  async deletePhoto<T extends Prisma.WedInvGalleryFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.WedInvGalleryFindUniqueArgs>
  ): Promise<PrismaWedInvGallery> {
    const { photo } = await this.prisma.wedInvGallery.findUniqueOrThrow({
      where: args.where,
    });

    await this.localStorageService.deleteFile(
      photo as unknown as LocalStorageFile
    );

    return await this.prisma.wedInvGallery.update({
      where: args.where,

      data: {
        photo: Prisma.DbNull,
      },
    });
  }

  async getWedInv(parentId: string): Promise<PrismaWedInv | null> {
    return this.prisma.wedInvGallery
      .findUnique({
        where: { id: parentId },
      })
      .wedInv();
  }
}
