/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  DtGift as PrismaDtGift,
  WedInvGift as PrismaWedInvGift,
} from "@prisma/client";
import { LocalStorageService } from "src/storage/providers/local/local.storage.service";
import { InputJsonValue } from "src/types";
import { FileDownload, FileUpload } from "src/storage/base/storage.types";
import { LocalStorageFile } from "src/storage/providers/local/local.storage.types";

export class DtGiftServiceBase {
  constructor(
    protected readonly prisma: PrismaService,
    protected readonly localStorageService: LocalStorageService
  ) {}

  async count(args: Omit<Prisma.DtGiftCountArgs, "select">): Promise<number> {
    return this.prisma.dtGift.count(args);
  }

  async dtGifts<T extends Prisma.DtGiftFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.DtGiftFindManyArgs>
  ): Promise<PrismaDtGift[]> {
    return this.prisma.dtGift.findMany<Prisma.DtGiftFindManyArgs>(args);
  }
  async dtGift<T extends Prisma.DtGiftFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.DtGiftFindUniqueArgs>
  ): Promise<PrismaDtGift | null> {
    return this.prisma.dtGift.findUnique(args);
  }
  async createDtGift<T extends Prisma.DtGiftCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.DtGiftCreateArgs>
  ): Promise<PrismaDtGift> {
    return this.prisma.dtGift.create<T>(args);
  }
  async updateDtGift<T extends Prisma.DtGiftUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.DtGiftUpdateArgs>
  ): Promise<PrismaDtGift> {
    return this.prisma.dtGift.update<T>(args);
  }
  async deleteDtGift<T extends Prisma.DtGiftDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.DtGiftDeleteArgs>
  ): Promise<PrismaDtGift> {
    return this.prisma.dtGift.delete(args);
  }

  async uploadIcon<T extends Prisma.DtGiftFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.DtGiftFindUniqueArgs>,
    file: FileUpload
  ): Promise<PrismaDtGift> {
    file.filename = `profilePicture-${args.where.id}.${file.filename
      .split(".")
      .pop()}`;
    const containerPath = "/DT/Gifts";
    const icon = await this.localStorageService.uploadFile(
      file,
      [],
      10000000,
      containerPath
    );

    return await this.prisma.dtGift.update({
      where: args.where,

      data: {
        icon: icon as InputJsonValue,
      },
    });
  }

  async downloadIcon<T extends Prisma.DtGiftFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.DtGiftFindUniqueArgs>
  ): Promise<FileDownload> {
    const { icon } = await this.prisma.dtGift.findUniqueOrThrow({
      where: args.where,
    });

    return await this.localStorageService.downloadFile(
      icon as unknown as LocalStorageFile
    );
  }

  async deleteIcon<T extends Prisma.DtGiftFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.DtGiftFindUniqueArgs>
  ): Promise<PrismaDtGift> {
    const { icon } = await this.prisma.dtGift.findUniqueOrThrow({
      where: args.where,
    });

    await this.localStorageService.deleteFile(
      icon as unknown as LocalStorageFile
    );

    return await this.prisma.dtGift.update({
      where: args.where,

      data: {
        icon: Prisma.DbNull,
      },
    });
  }

  async findWedInvGifts(
    parentId: string,
    args: Prisma.WedInvGiftFindManyArgs
  ): Promise<PrismaWedInvGift[]> {
    return this.prisma.dtGift
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .wedInvGifts(args);
  }
}
