/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumWedInvStatus } from "./EnumWedInvStatus";
import { IsEnum, IsOptional, IsString, ValidateNested } from "class-validator";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { Type } from "class-transformer";
import { WedInvCommentCreateNestedManyWithoutWedInvsInput } from "./WedInvCommentCreateNestedManyWithoutWedInvsInput";
import { WedInvEventCreateNestedManyWithoutWedInvsInput } from "./WedInvEventCreateNestedManyWithoutWedInvsInput";
import { WedInvGalleryCreateNestedManyWithoutWedInvsInput } from "./WedInvGalleryCreateNestedManyWithoutWedInvsInput";
import { WedInvGiftCreateNestedManyWithoutWedInvsInput } from "./WedInvGiftCreateNestedManyWithoutWedInvsInput";
import { WedInvPaymentCreateNestedManyWithoutWedInvsInput } from "./WedInvPaymentCreateNestedManyWithoutWedInvsInput";
import { WedInvPresetCreateNestedManyWithoutWedInvsInput } from "./WedInvPresetCreateNestedManyWithoutWedInvsInput";
import { WedInvShareCreateNestedManyWithoutWedInvsInput } from "./WedInvShareCreateNestedManyWithoutWedInvsInput";
import { WedInvStoryCreateNestedManyWithoutWedInvsInput } from "./WedInvStoryCreateNestedManyWithoutWedInvsInput";
import { WedInvVideoCreateNestedManyWithoutWedInvsInput } from "./WedInvVideoCreateNestedManyWithoutWedInvsInput";
import { WedInvWeddingCreateNestedManyWithoutWedInvsInput } from "./WedInvWeddingCreateNestedManyWithoutWedInvsInput";

@InputType()
class WedInvCreateInput {
  @ApiProperty({
    required: false,
    enum: EnumWedInvStatus,
  })
  @IsEnum(EnumWedInvStatus)
  @IsOptional()
  @Field(() => EnumWedInvStatus, {
    nullable: true,
  })
  status?: "Active" | "Nonactive" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  url?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => WedInvCommentCreateNestedManyWithoutWedInvsInput,
  })
  @ValidateNested()
  @Type(() => WedInvCommentCreateNestedManyWithoutWedInvsInput)
  @IsOptional()
  @Field(() => WedInvCommentCreateNestedManyWithoutWedInvsInput, {
    nullable: true,
  })
  wedInvComments?: WedInvCommentCreateNestedManyWithoutWedInvsInput;

  @ApiProperty({
    required: false,
    type: () => WedInvEventCreateNestedManyWithoutWedInvsInput,
  })
  @ValidateNested()
  @Type(() => WedInvEventCreateNestedManyWithoutWedInvsInput)
  @IsOptional()
  @Field(() => WedInvEventCreateNestedManyWithoutWedInvsInput, {
    nullable: true,
  })
  wedInvEvents?: WedInvEventCreateNestedManyWithoutWedInvsInput;

  @ApiProperty({
    required: false,
    type: () => WedInvGalleryCreateNestedManyWithoutWedInvsInput,
  })
  @ValidateNested()
  @Type(() => WedInvGalleryCreateNestedManyWithoutWedInvsInput)
  @IsOptional()
  @Field(() => WedInvGalleryCreateNestedManyWithoutWedInvsInput, {
    nullable: true,
  })
  wedInvGalleries?: WedInvGalleryCreateNestedManyWithoutWedInvsInput;

  @ApiProperty({
    required: false,
    type: () => WedInvGiftCreateNestedManyWithoutWedInvsInput,
  })
  @ValidateNested()
  @Type(() => WedInvGiftCreateNestedManyWithoutWedInvsInput)
  @IsOptional()
  @Field(() => WedInvGiftCreateNestedManyWithoutWedInvsInput, {
    nullable: true,
  })
  wedInvGifts?: WedInvGiftCreateNestedManyWithoutWedInvsInput;

  @ApiProperty({
    required: false,
    type: () => WedInvPaymentCreateNestedManyWithoutWedInvsInput,
  })
  @ValidateNested()
  @Type(() => WedInvPaymentCreateNestedManyWithoutWedInvsInput)
  @IsOptional()
  @Field(() => WedInvPaymentCreateNestedManyWithoutWedInvsInput, {
    nullable: true,
  })
  wedInvPayments?: WedInvPaymentCreateNestedManyWithoutWedInvsInput;

  @ApiProperty({
    required: false,
    type: () => WedInvPresetCreateNestedManyWithoutWedInvsInput,
  })
  @ValidateNested()
  @Type(() => WedInvPresetCreateNestedManyWithoutWedInvsInput)
  @IsOptional()
  @Field(() => WedInvPresetCreateNestedManyWithoutWedInvsInput, {
    nullable: true,
  })
  wedInvPresets?: WedInvPresetCreateNestedManyWithoutWedInvsInput;

  @ApiProperty({
    required: false,
    type: () => WedInvShareCreateNestedManyWithoutWedInvsInput,
  })
  @ValidateNested()
  @Type(() => WedInvShareCreateNestedManyWithoutWedInvsInput)
  @IsOptional()
  @Field(() => WedInvShareCreateNestedManyWithoutWedInvsInput, {
    nullable: true,
  })
  wedInvShares?: WedInvShareCreateNestedManyWithoutWedInvsInput;

  @ApiProperty({
    required: false,
    type: () => WedInvStoryCreateNestedManyWithoutWedInvsInput,
  })
  @ValidateNested()
  @Type(() => WedInvStoryCreateNestedManyWithoutWedInvsInput)
  @IsOptional()
  @Field(() => WedInvStoryCreateNestedManyWithoutWedInvsInput, {
    nullable: true,
  })
  wedInvStories?: WedInvStoryCreateNestedManyWithoutWedInvsInput;

  @ApiProperty({
    required: false,
    type: () => WedInvVideoCreateNestedManyWithoutWedInvsInput,
  })
  @ValidateNested()
  @Type(() => WedInvVideoCreateNestedManyWithoutWedInvsInput)
  @IsOptional()
  @Field(() => WedInvVideoCreateNestedManyWithoutWedInvsInput, {
    nullable: true,
  })
  wedInvVideos?: WedInvVideoCreateNestedManyWithoutWedInvsInput;

  @ApiProperty({
    required: false,
    type: () => WedInvWeddingCreateNestedManyWithoutWedInvsInput,
  })
  @ValidateNested()
  @Type(() => WedInvWeddingCreateNestedManyWithoutWedInvsInput)
  @IsOptional()
  @Field(() => WedInvWeddingCreateNestedManyWithoutWedInvsInput, {
    nullable: true,
  })
  wedInvWeddings?: WedInvWeddingCreateNestedManyWithoutWedInvsInput;
}

export { WedInvCreateInput as WedInvCreateInput };
