/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, IsEnum, ValidateNested } from "class-validator";
import { EnumWedInvStatus } from "./EnumWedInvStatus";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { WedInvCommentListRelationFilter } from "../../wedInvComment/base/WedInvCommentListRelationFilter";
import { WedInvEventListRelationFilter } from "../../wedInvEvent/base/WedInvEventListRelationFilter";
import { WedInvGalleryListRelationFilter } from "../../wedInvGallery/base/WedInvGalleryListRelationFilter";
import { WedInvGiftListRelationFilter } from "../../wedInvGift/base/WedInvGiftListRelationFilter";
import { WedInvPaymentListRelationFilter } from "../../wedInvPayment/base/WedInvPaymentListRelationFilter";
import { WedInvPresetListRelationFilter } from "../../wedInvPreset/base/WedInvPresetListRelationFilter";
import { WedInvShareListRelationFilter } from "../../wedInvShare/base/WedInvShareListRelationFilter";
import { WedInvStoryListRelationFilter } from "../../wedInvStory/base/WedInvStoryListRelationFilter";
import { WedInvVideoListRelationFilter } from "../../wedInvVideo/base/WedInvVideoListRelationFilter";
import { WedInvWeddingListRelationFilter } from "../../wedInvWedding/base/WedInvWeddingListRelationFilter";

@InputType()
class WedInvWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    enum: EnumWedInvStatus,
  })
  @IsEnum(EnumWedInvStatus)
  @IsOptional()
  @Field(() => EnumWedInvStatus, {
    nullable: true,
  })
  status?: "Active" | "Nonactive";

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  url?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => WedInvCommentListRelationFilter,
  })
  @ValidateNested()
  @Type(() => WedInvCommentListRelationFilter)
  @IsOptional()
  @Field(() => WedInvCommentListRelationFilter, {
    nullable: true,
  })
  wedInvComments?: WedInvCommentListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => WedInvEventListRelationFilter,
  })
  @ValidateNested()
  @Type(() => WedInvEventListRelationFilter)
  @IsOptional()
  @Field(() => WedInvEventListRelationFilter, {
    nullable: true,
  })
  wedInvEvents?: WedInvEventListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => WedInvGalleryListRelationFilter,
  })
  @ValidateNested()
  @Type(() => WedInvGalleryListRelationFilter)
  @IsOptional()
  @Field(() => WedInvGalleryListRelationFilter, {
    nullable: true,
  })
  wedInvGalleries?: WedInvGalleryListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => WedInvGiftListRelationFilter,
  })
  @ValidateNested()
  @Type(() => WedInvGiftListRelationFilter)
  @IsOptional()
  @Field(() => WedInvGiftListRelationFilter, {
    nullable: true,
  })
  wedInvGifts?: WedInvGiftListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => WedInvPaymentListRelationFilter,
  })
  @ValidateNested()
  @Type(() => WedInvPaymentListRelationFilter)
  @IsOptional()
  @Field(() => WedInvPaymentListRelationFilter, {
    nullable: true,
  })
  wedInvPayments?: WedInvPaymentListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => WedInvPresetListRelationFilter,
  })
  @ValidateNested()
  @Type(() => WedInvPresetListRelationFilter)
  @IsOptional()
  @Field(() => WedInvPresetListRelationFilter, {
    nullable: true,
  })
  wedInvPresets?: WedInvPresetListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => WedInvShareListRelationFilter,
  })
  @ValidateNested()
  @Type(() => WedInvShareListRelationFilter)
  @IsOptional()
  @Field(() => WedInvShareListRelationFilter, {
    nullable: true,
  })
  wedInvShares?: WedInvShareListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => WedInvStoryListRelationFilter,
  })
  @ValidateNested()
  @Type(() => WedInvStoryListRelationFilter)
  @IsOptional()
  @Field(() => WedInvStoryListRelationFilter, {
    nullable: true,
  })
  wedInvStories?: WedInvStoryListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => WedInvVideoListRelationFilter,
  })
  @ValidateNested()
  @Type(() => WedInvVideoListRelationFilter)
  @IsOptional()
  @Field(() => WedInvVideoListRelationFilter, {
    nullable: true,
  })
  wedInvVideos?: WedInvVideoListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => WedInvWeddingListRelationFilter,
  })
  @ValidateNested()
  @Type(() => WedInvWeddingListRelationFilter)
  @IsOptional()
  @Field(() => WedInvWeddingListRelationFilter, {
    nullable: true,
  })
  wedInvWeddings?: WedInvWeddingListRelationFilter;
}

export { WedInvWhereInput as WedInvWhereInput };
