/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumWedInvStatus } from "./EnumWedInvStatus";
import { IsEnum, IsOptional, IsString, ValidateNested } from "class-validator";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { Type } from "class-transformer";
import { WedInvCommentUpdateManyWithoutWedInvsInput } from "./WedInvCommentUpdateManyWithoutWedInvsInput";
import { WedInvEventUpdateManyWithoutWedInvsInput } from "./WedInvEventUpdateManyWithoutWedInvsInput";
import { WedInvGalleryUpdateManyWithoutWedInvsInput } from "./WedInvGalleryUpdateManyWithoutWedInvsInput";
import { WedInvGiftUpdateManyWithoutWedInvsInput } from "./WedInvGiftUpdateManyWithoutWedInvsInput";
import { WedInvPaymentUpdateManyWithoutWedInvsInput } from "./WedInvPaymentUpdateManyWithoutWedInvsInput";
import { WedInvPresetUpdateManyWithoutWedInvsInput } from "./WedInvPresetUpdateManyWithoutWedInvsInput";
import { WedInvShareUpdateManyWithoutWedInvsInput } from "./WedInvShareUpdateManyWithoutWedInvsInput";
import { WedInvStoryUpdateManyWithoutWedInvsInput } from "./WedInvStoryUpdateManyWithoutWedInvsInput";
import { WedInvVideoUpdateManyWithoutWedInvsInput } from "./WedInvVideoUpdateManyWithoutWedInvsInput";
import { WedInvWeddingUpdateManyWithoutWedInvsInput } from "./WedInvWeddingUpdateManyWithoutWedInvsInput";

@InputType()
class WedInvUpdateInput {
  @ApiProperty({
    required: false,
    enum: EnumWedInvStatus,
  })
  @IsEnum(EnumWedInvStatus)
  @IsOptional()
  @Field(() => EnumWedInvStatus, {
    nullable: true,
  })
  status?: "Active" | "Nonactive" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  url?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => WedInvCommentUpdateManyWithoutWedInvsInput,
  })
  @ValidateNested()
  @Type(() => WedInvCommentUpdateManyWithoutWedInvsInput)
  @IsOptional()
  @Field(() => WedInvCommentUpdateManyWithoutWedInvsInput, {
    nullable: true,
  })
  wedInvComments?: WedInvCommentUpdateManyWithoutWedInvsInput;

  @ApiProperty({
    required: false,
    type: () => WedInvEventUpdateManyWithoutWedInvsInput,
  })
  @ValidateNested()
  @Type(() => WedInvEventUpdateManyWithoutWedInvsInput)
  @IsOptional()
  @Field(() => WedInvEventUpdateManyWithoutWedInvsInput, {
    nullable: true,
  })
  wedInvEvents?: WedInvEventUpdateManyWithoutWedInvsInput;

  @ApiProperty({
    required: false,
    type: () => WedInvGalleryUpdateManyWithoutWedInvsInput,
  })
  @ValidateNested()
  @Type(() => WedInvGalleryUpdateManyWithoutWedInvsInput)
  @IsOptional()
  @Field(() => WedInvGalleryUpdateManyWithoutWedInvsInput, {
    nullable: true,
  })
  wedInvGalleries?: WedInvGalleryUpdateManyWithoutWedInvsInput;

  @ApiProperty({
    required: false,
    type: () => WedInvGiftUpdateManyWithoutWedInvsInput,
  })
  @ValidateNested()
  @Type(() => WedInvGiftUpdateManyWithoutWedInvsInput)
  @IsOptional()
  @Field(() => WedInvGiftUpdateManyWithoutWedInvsInput, {
    nullable: true,
  })
  wedInvGifts?: WedInvGiftUpdateManyWithoutWedInvsInput;

  @ApiProperty({
    required: false,
    type: () => WedInvPaymentUpdateManyWithoutWedInvsInput,
  })
  @ValidateNested()
  @Type(() => WedInvPaymentUpdateManyWithoutWedInvsInput)
  @IsOptional()
  @Field(() => WedInvPaymentUpdateManyWithoutWedInvsInput, {
    nullable: true,
  })
  wedInvPayments?: WedInvPaymentUpdateManyWithoutWedInvsInput;

  @ApiProperty({
    required: false,
    type: () => WedInvPresetUpdateManyWithoutWedInvsInput,
  })
  @ValidateNested()
  @Type(() => WedInvPresetUpdateManyWithoutWedInvsInput)
  @IsOptional()
  @Field(() => WedInvPresetUpdateManyWithoutWedInvsInput, {
    nullable: true,
  })
  wedInvPresets?: WedInvPresetUpdateManyWithoutWedInvsInput;

  @ApiProperty({
    required: false,
    type: () => WedInvShareUpdateManyWithoutWedInvsInput,
  })
  @ValidateNested()
  @Type(() => WedInvShareUpdateManyWithoutWedInvsInput)
  @IsOptional()
  @Field(() => WedInvShareUpdateManyWithoutWedInvsInput, {
    nullable: true,
  })
  wedInvShares?: WedInvShareUpdateManyWithoutWedInvsInput;

  @ApiProperty({
    required: false,
    type: () => WedInvStoryUpdateManyWithoutWedInvsInput,
  })
  @ValidateNested()
  @Type(() => WedInvStoryUpdateManyWithoutWedInvsInput)
  @IsOptional()
  @Field(() => WedInvStoryUpdateManyWithoutWedInvsInput, {
    nullable: true,
  })
  wedInvStories?: WedInvStoryUpdateManyWithoutWedInvsInput;

  @ApiProperty({
    required: false,
    type: () => WedInvVideoUpdateManyWithoutWedInvsInput,
  })
  @ValidateNested()
  @Type(() => WedInvVideoUpdateManyWithoutWedInvsInput)
  @IsOptional()
  @Field(() => WedInvVideoUpdateManyWithoutWedInvsInput, {
    nullable: true,
  })
  wedInvVideos?: WedInvVideoUpdateManyWithoutWedInvsInput;

  @ApiProperty({
    required: false,
    type: () => WedInvWeddingUpdateManyWithoutWedInvsInput,
  })
  @ValidateNested()
  @Type(() => WedInvWeddingUpdateManyWithoutWedInvsInput)
  @IsOptional()
  @Field(() => WedInvWeddingUpdateManyWithoutWedInvsInput, {
    nullable: true,
  })
  wedInvWeddings?: WedInvWeddingUpdateManyWithoutWedInvsInput;
}

export { WedInvUpdateInput as WedInvUpdateInput };
